src/App.global.less, src/components/OutputCell.tsx, src/redux/actions/editor.ts, src/types/notebook.ts
=> Support pandas rich html outputs

README.md, src/components/NotebookCell.tsx, src/kernel/useKernel.ts, src/kernel/useKernelStatus.ts, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/types/redux/editor.ts
=> Add kernel disconnect

src/components/NotebookCell.tsx, src/kernel/useKernel.ts, src/kernel/useKernelStatus.ts, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/types/redux/editor.ts
Closes #123
Closes #119
Closes #118
=> Allow cells to be queued and separate selected cell from locked cell

src/components/NotebookCell.tsx, src/kernel/useKernel.ts, src/pages/EditorPage/RightSidebar/DownloadsPanel.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/pages/EditorPage/index.tsx, src/redux/editor.ts, src/utils/notebook.ts, src/utils/spreadable.ts
=> Use records for cells in redux

.eslintrc.aggressive.json, package.json, src/components/CodeCell.tsx, src/components/MarkdownCell.tsx, src/components/NotebookCell.tsx, src/components/OutputCell.tsx, src/constants/notebook.ts, src/kernel/useKernel.ts, src/pages/AuthPage/index.tsx, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/pages/EditorPage/index.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/types/immutable.ts, src/types/kernel.ts, src/types/notebook.ts, src/utils/notebook.ts, yarn.lock
=> Use Immutable.js in editor redux

src/components/OutputCell.tsx, src/pages/AuthPage/index.tsx, src/redux/editor.ts, src/utils/notebook.ts
=> Converted outputs from list to nested map

src/constants/demo.ts, src/constants/notebook.ts, src/redux/editor.ts, src/types/notebook.ts, src/utils/immutable/helper.ts, src/utils/immutable/kernel.ts, src/utils/immutable/notebook.ts, src/utils/notebook.ts
=> Build immutables with consistent functions

src/api/kernel.ts, src/kernel/useKernel.ts, src/redux/actions/editor.ts, src/redux/editor.ts, src/types/redux/editor.ts
=> Restarted kernel on project change

src/components/NotebookCell.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts
=> Fix auto-unlock race condition

src/api/kernel.ts, src/kernel/useKernel.ts, src/kernel/useKernelStatus.ts, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/actions/index.ts, src/redux/editor.ts, src/redux/index.ts, src/redux/middleware/ReduxKernel.ts, src/redux/middleware/ReduxSocketClient.ts, src/types/kernel.ts, src/types/redux/editor.ts
=> Move kernel to middleware

src/api/kernel.ts, src/redux/middleware/ReduxKernel.ts, src/utils/sleep.ts
=> Moved listeners to redux kernel middleware, removed on disconnect

src/redux/actions/editor.ts, src/redux/editor.ts, src/types/redux/editor.ts
=> Immediately apply code changes and prevent debounce from overwriting

src/utils/notebook.ts, src/utils/regex.ts
=> Replaced negative lookbehind with regex match

src/redux/auth.ts, src/redux/editor.ts, src/redux/ui.ts
=> Improve redux documentation

src/redux/actions/auth.ts, src/redux/auth.ts, src/redux/editor.ts, src/redux/middleware/ReduxSocketClient.ts, src/redux/ui.ts
=> Disconnect from socket and kernel on sign out

src/components/NotebookCell.tsx, src/components/Timer.tsx, src/components/index.tsx, src/redux/middleware/ReduxKernel.ts
=> Execution timer

src/pages/AuthPage/index.tsx, src/redux/actions/auth.ts, src/redux/auth.ts, src/redux/middleware/ReduxSocketClient.ts, src/types/redux/auth.ts
Updated in accordance with changes https://github.com/actually-colab/editor/pull/90
=> Update store to refresh session tokens on login

src/components/NotebookCell.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxSocketClient.ts, src/types/notebook.ts, src/types/redux/editor.ts
=> Separate DCell changes and editor cell metadata changes

src/redux/editor.ts
=> Prevent currently running cell from being added to the queue

src/constants/demo.ts, src/redux/actions/auth.ts, src/redux/middleware/ReduxEditorClient.ts, src/utils/storage.ts
=> Automatically open the most recently opened notebook

src/components/PopoverDropdown.tsx, src/components/RegularIconButton.tsx, src/components/index.tsx, src/pages/EditorPage/components/EditorHeader.tsx
=> Improved header to make buttons more clear

src/redux/editor.ts
=> Ignore edits that come from the current user to avoid race condition

src/App.global.less, src/components/MarkdownCell.tsx
=> Render placeholder content if markdown is empty

src/App.global.less, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/redux/actions/editor.ts
=> Replaced kernel logs with a timeline

src/components/PopoverDropdown.tsx, src/pages/EditorPage/RightSidebar/DownloadsPanel.tsx, src/utils/notebook.ts
=> Added support for downloading as python and markdown

src/App.global.less, src/components/CodeCell.tsx, src/components/UserAvatar.tsx, src/immutable/notebook.ts, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/pages/EditorPage/RightSidebar/CollaboratorsPanel.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts, src/utils/date.ts
=> Implement collaborators panel

src/components/UserAvatar.tsx, src/immutable/kernel.ts, src/immutable/notebook.ts
=> Support user profile pictures

src/components/UserAvatar.tsx, src/immutable/index.ts, src/immutable/user.ts, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Store active users and render them in the editor header

src/components/NotebookCell.tsx
=> Render lock owners on cells instead of hardcoded data

src/components/NotebookCell.tsx, src/components/OutputCell.tsx, src/immutable/notebook.ts, src/pages/EditorPage/RightSidebar/DownloadsPanel.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/notebook.ts, src/types/redux/editor.ts, src/utils/notebook.ts, yarn.lock
Closes #238
Closes #239 
Closes #240
=> View user outputs live

src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/redux/middleware/ReduxKernel.ts, src/types/notebook.ts, src/types/redux/editor.ts, src/utils/notebook.ts
=> Store metadata in output strings and minimize kernel messages

src/kernel/useKernel.ts, src/redux/middleware/ReduxEditorClient.ts
=> Moved kernel restarting to redux middleware

src/pages/EditorPage/Header/CollaboratorsPopover.tsx, src/pages/EditorPage/Header/index.tsx, src/pages/EditorPage/RightSidebar/index.tsx, src/pages/EditorPage/components/EditorHeader.tsx, src/pages/EditorPage/components/RightSidebar.tsx
=> Moved share button to popover on header

src/redux/middleware/ReduxEditorClient.ts, src/redux/middleware/ReduxKernel.ts
=> Show login error notifications

src/components/CodeCell.tsx, src/components/NotebookCell.tsx
=> Update cursor on focus and fix unknown lock owner issue

src/pages/EditorPage/components/EditorHeader.tsx, src/redux/actions/auth.ts, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Use notebook_contents event. Replaced user list with OrderedSet. Fixed header alignment bug

src/components/NotebookCell.tsx, src/components/OutputCell.tsx, src/immutable/notebook.ts, src/pages/EditorPage/RightSidebar/DownloadsPanel.tsx, src/redux/editor.ts, src/types/notebook.ts, src/utils/notebook.ts
=> Store output metadata in redux to view echoed outputs before selecting

src/pages/EditorPage/components/EditorHeader.tsx
=> Clarified kernel selector with icon and viewing email

src/components/NotebookCell.tsx, src/pages/EditorPage/Header/CollaboratorsPopover.tsx, src/pages/EditorPage/components/EditorHeader.tsx
=> Respect access levels

src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/utils/notebook.ts
=> Added ability to sort notebooks by name or last modified

src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/utils/notebook.ts
=> Filter notebooks by name using search field

src/components/PopoverDropdown.tsx, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx
=> Added popover to select notebook or workshop type

src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/pages/EditorPage/components/LeftSidebar.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/types/redux/editor.ts, src/utils/notebook.ts, src/utils/redirect.ts, src/utils/storage.ts
=> Hardcoded workshop panel

src/immutable/notebook.ts, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/pages/EditorPage/hooks/useNotebooks.ts, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Implement fetching workshops

src/components/UserAvatar.tsx, src/pages/EditorPage/Header/CollaboratorsPopover.tsx, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts, src/utils/notebook.ts
=> Share workshops

src/redux/middleware/ReduxEditorClient.ts
=> Add support for deleting cells

src/App.global.less, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/redux/actions/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts, src/utils/notebook.ts
=> Allow users to upload notebooks instead of create blank ones

src/pages/EditorPage/Header/CollaboratorsPopover.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts, src/utils/notebook.ts
=> Unshare notebooks

src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Update notebook time_modified on edit

src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx
=> Clear uploader when opening new project dialog

src/immutable/notebook.ts, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/pages/EditorPage/RightSidebar/ChatPanel.tsx, src/pages/EditorPage/RightSidebar/CommentsPanel.tsx, src/pages/EditorPage/RightSidebar/DownloadsPanel.tsx, src/pages/EditorPage/RightSidebar/SettingsPanel.tsx, src/pages/EditorPage/RightSidebar/StatsPanel.tsx, src/pages/EditorPage/RightSidebar/index.tsx, src/pages/EditorPage/components/RightSidebar.tsx, src/redux/actions/editor.ts, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Chat panel

src/immutable/notebook.ts, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/utils/notebook.ts
=> Workshop attendee notebooks

src/redux/middleware/ReduxEditorClient.ts
=> Auto refresh notebooks and workshops when a workshop is released

src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/redux/middleware/ReduxEditorClient.ts
=> Auto open created notebook or workshop

src/components/NotebookCell.tsx
=> Auto scroll to cell when selected

.gitignore, .sentryclirc, README.md, package.json, scripts/sentry.js, src/index.tsx, yarn.lock
=> Configure sentry

package.json, src/App.global.less
=> Fix markdown spacing issues

src/components/OutputCell.tsx, src/redux/editor.ts, src/redux/middleware/ReduxEditorClient.ts, src/utils/notebook.ts
=> Improve efficiency of immutable outputs

src/App.global.less, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/redux/editor.ts, src/redux/middleware/ReduxKernel.ts, src/types/redux/editor.ts, src/utils/storage.ts
=> Remember gateway uris

src/components/NotebookCell.tsx, src/redux/editor.reducer.ts
=> Anchor scroll to cell

src/components/NotebookCell.tsx
=> Reset scroll anchors when no cell is locked

.github/workflows/bundle-reporter.yml, .github/workflows/validation.yml, package.json, yarn.lock
=> Use the deployed editor client and editor types packages

src/redux/editor.reducer.ts
=> Fixed bug where running cell with new kernel duplicated outputs

src/components/NotebookCell/CellToolbar.tsx, src/components/NotebookCell/CodeCell.tsx, src/components/NotebookCell/MarkdownCell.tsx, src/components/NotebookCell/OutputCell.tsx, src/components/NotebookCell/RunIndicator.tsx, src/components/NotebookCell/index.tsx, src/components/index.tsx, src/redux/actions/editor.actions.ts, src/redux/editor.reducer.ts, src/redux/middleware/ReduxEditorClient.ts
Closes #360 
Closes #357
Closes #356
=> Decompose notebook cell

src/redux/editor.reducer.ts
=> Fixed bug where cell_id wasn't deleted from notebook

src/redux/middleware/ReduxEditorClient.ts
=> Display error messages from socket client

src/App.global.less, src/components/NotebookCell/CodeCell.tsx, src/components/NotebookCell/index.tsx
=> Show user's names on cursor markers

src/components/NotebookCell/CodeCell.tsx, src/components/Timer.tsx
=> Hide the cursor label after a period of inactivity

src/App.global.less
=> Fix selection marker hiding code

src/redux/middleware/ReduxEditorClient.ts
=> Auto render markdown cells on unlock

src/kernel/useKernel.ts, src/redux/editor.reducer.ts, src/redux/middleware/ReduxEditorClient.ts, src/redux/middleware/ReduxKernel.ts
=> Move kernel run queue from hook to middleware

.env.development, .env.production, src/constants/env.ts, src/constants/logging.ts, src/pages/AuthPage/index.tsx, src/pages/EditorPage/LeftSidebar/ProjectsPanel.tsx, src/redux/actions/auth.actions.ts, src/redux/middleware/ReduxEditorClient.ts, src/redux/middleware/ReduxKernel.ts
=> Decreased the amount of logging in prod

README.md, package.json, src/api/kernel.ts, src/redux/middleware/ReduxKernel.ts, yarn.lock
=> Jupyterlab services

kernel.dev.sh, package.json
=> Added start:kernel:dev:autoclean script

src/App.global.less, src/kernel/useKernel.ts, src/pages/EditorPage/LeftSidebar/KernelPanel.tsx, src/redux/actions/editor.actions.ts, src/redux/editor.reducer.ts, src/redux/middleware/ReduxKernel.ts, src/types/redux/editor.ts
=> Kernel tokens

src/pages/EditorPage/LeftSidebar/KernelPanel.tsx
=> Make it more obvious that the kernel token is required

src/App.global.less
=> Fix color of active timeline dot

src/pages/EditorPage/LeftSidebar/KernelPanel/KernelLogs.tsx
=> Reversed the order of the timeline to have newest items at top

src/api/kernel.ts, src/kernel/useKernel.ts, src/redux/middleware/ReduxKernel.ts
=> Fix issue where kernel would poll even without automatic connect

src/components/ColoredIconButton.tsx, src/components/IconTextButton.tsx, src/components/NotebookCell/CellToolbar.tsx, src/contexts/ContainerContext.tsx, src/pages/EditorPage/components/EditorBody.tsx, src/pages/EditorPage/components/RightSidebar.tsx
=> Add a dropdown menu to each cell with advanced actions

src/redux/actions/editor.actions.ts, src/redux/editor.reducer.ts, src/utils/storage.ts
=> Remember auto connect preference in storage

src/pages/EditorPage/Header/index.tsx, src/pages/EditorPage/components/EditorHeader/ActionButtons/CellButtons.tsx, src/pages/EditorPage/components/EditorHeader/ActionButtons/ExecutionButtons.tsx, src/pages/EditorPage/components/EditorHeader/ActionButtons/index.tsx, src/pages/EditorPage/components/EditorHeader/CollaboratorsPopover.tsx, src/pages/EditorPage/components/EditorHeader/KernelSelector.tsx, src/pages/EditorPage/components/EditorHeader/UserAvatarList.tsx, src/pages/EditorPage/components/EditorHeader/index.tsx
=> Decompose editor header to improve performance

src/components/PopoverDropdown.tsx, src/pages/EditorPage/components/EditorHeader/KernelSelector.tsx
=> Improved UI for kernel selector to make it more obvious

src/pages/EditorPage/components/EditorHeader/KernelSelector.tsx
=> Add descriptive information to kernel selector

src/components/MonacoEditor/completionProvider.ts, src/components/MonacoEditor/index.tsx, src/components/NotebookCell/CodeCell.tsx, src/redux/middleware/ReduxKernel.ts, src/utils/completions.ts
Currently experimental but should work when connected to a kernel
=> Added code completions from Jupyter

src/redux/middleware/ReduxEditorClient.ts
=> Fixed issue where kernel would restart even when unused

src/components/MonacoEditor/index.tsx
=> Fix issue with monaco preventing undo/redo working

src/components/NotebookCell/CellToolbar.tsx, src/components/Timer.tsx
=> Fix issue where timer nonce was changed by switching users

src/components/NotebookCell/RunIndicator.tsx, src/redux/editor.reducer.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/notebook.ts
=> Send running status with cell outputs

src/redux/editor.reducer.ts, src/redux/middleware/ReduxKernel.ts, src/utils/storage.ts
=> Remember token to the most recently connected kernel

src/components/NotebookCell/CodeCell.tsx
=> Added an inner shadow to locked cells based on the user color

src/components/MonacoEditor/index.tsx
=> Use applyEdits and forceTokenization to fix flickering on edit events

src/pages/EditorPage/components/EditorHeader/KernelSelector.tsx
=> Added status indicator and separated active/inactive users in selector

src/components/NotebookCell/CellToolbar.tsx
=> Added view/render to markdown cell menu and run to python cell menu

src/redux/actions/editor.actions.ts, src/redux/middleware/ReduxEditorClient.ts, src/types/redux/editor.ts
=> Auto reconnect when socket connection times out

src/components/MonacoEditor/themes/xcode.ts
=> Changed the color of monaco line numbers

src/components/NotebookCell/CodeCell.tsx, src/components/UserAvatar.tsx, src/utils/color.ts
=> Generate darker colors for users to make them easier to read

src/pages/EditorPage/index.tsx
=> Show a connecting modal when reconnecting to socket client

src/pages/EditorPage/components/EditorHeader/UserAvatarList.tsx
=> Display a popover list of users when more than 3 users are active

src/pages/EditorPage/components/EditorHeader/KernelSelector.tsx
=> Added user avatars and names to kernel selector

src/pages/EditorPage/components/LeftSidebar.tsx
=> Remove unused left sidebar panels

src/components/NotebookCell/CellToolbar.tsx
=> Replaced action menu icon with a less confusing icon

src/components/UserAvatar.tsx, src/pages/EditorPage/components/EditorHeader/ProfileButton.tsx, src/pages/EditorPage/components/EditorHeader/index.tsx, src/pages/EditorPage/components/LeftSidebar.tsx
=> Moved profile button to editor header

src/components/NotebookCell/CellToolbar.tsx
=> Change lock owner color to match user color

src/pages/EditorPage/components/EditorHeader/KernelSelector/KernelLogs.tsx
=> Added a launch kernel button to the kernel config modal

src/api/kernel.ts, src/components/MonacoEditor/completionProvider.ts, src/index.tsx, src/pages/EditorPage/components/EditorHeader/ActionButtons/CellButtons.tsx, src/redux/editor.reducer.ts, src/redux/middleware/ReduxEditorClient.ts, src/redux/middleware/ReduxKernel.ts
=> Decrease console logs in production

src/redux/middleware/ReduxKernel.ts
=> Added a notification when kernel is connected
